# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: eslint project check
        run: make lint
